---
title: "Homework 4 Dashboard - Exploring the Bakery Section of the Instacart Dataset"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r dashboard setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

```

```{r}
instacart_data = p8105.datasets::instacart %>% 
    janitor::clean_names()
```

Column {data-width=600}
-----------------------------------------------------------------------

### Count of Number of Items Ordered Each Hour of Day by Bakery Aisle

```{r}
instacart_data %>%
  filter(department == "bakery" & order_dow == 0) %>% 
  group_by(aisle, order_hour_of_day) %>% 
  mutate(n = n()) %>% 
  plot_ly(x = ~order_hour_of_day, y = ~n, type = "scatter", mode = "line",
          alpha = 0.5, 
          color = ~aisle)
```

Column {data-width=400}
-----------------------------------------------------------------------

### Barchart Of The Total Number of Items Ordered Per Aisle in Bakery Department 

```{r}
instacart_data %>%
  filter(department == "bakery") %>% 
  group_by(aisle) %>% 
  summarize(n = n()) %>%
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar")
```

### Boxplots Comparing Distributions of Order Hour of Day by Bakery Aisle

```{r}
instacart_data %>%
  filter(department == "bakery") %>% 
  plot_ly(y = ~order_hour_of_day, color = ~aisle, type = "box",
          colors = "Set2")

```

