---
title: "Devon Morgan, MS"
output: 
  html_document 
---
#### Epidemiology | Biostatistics and Data Analysis | Project Management | Columbia and Johns Hopkins Graduate

I am an epidemiologist interested in applying my knowledge of epidemiological methods, study design, and biostatistics/data analysis to solving problems within the real world evidence/pharmacoepidemiology space. I have substantial experience in epidemiological research (with a focus on cancer epidemiology), data analysis, technical writing, systematic reviews, and project management. I have work experience in a diverse range of settings including a biopharmaceutical company, technical consulting firm, and traditional academic research.

I recently completed a Master of Science degree in Epidemiology at Columbia University Mailman School of Public Health. I previously graduated Phi Beta Kappa from Johns Hopkins University with a bachelor's degree in Biology (minor in Psychology). 

Outside of work, you can find me trying a new recipe, exploring an art museum, running, or attempting my latest hobby - bird watching.

#### Contact Information

Devon Morgan

Email: dm3175@columbia.edu

Resume available upon request.

[Linkedin](https://www.linkedin.com/in/devonmorgan533/)
